settings:
  title: 'Status Page'
  url: 'https://status.androidacy.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: website # unique identifier
    name: Website
    description: 'The Androidacy website and web apps' # default=empty
    url: 'https://www.androidacy.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: production-api
    name: API
    description: 'Our rich and powerful API powers our website, apps, and more.'
    url: 'https://production-api.androidacy.com/ping'
    method: GET
    expectStatus: 204
    linkable: true # allows the title to be a link, default=true

  - id: vaultwarden
    name: Vaultwarden Host
    description: 'Vaultwarden is a safe place to dtore your passwords, compatible with Bitwarden.'
    url: 'https://bw.androidacy.com/'
    method: GET
    expectStatus: 200
    linkable: true
